[project]
name = "comfyui-if_ai_parlerttsnode"
description = "Parler TTS is a zeroshot voice synthesis with emotion and entonations, you can control the voice style via text prompt"
version = "1.0.0"
license = { file = "LICENSE" }

[project.urls]
Repository = "https://github.com/if-ai/ComfyUI-IF_AI_ParlerTTSNode"
#  Used by Comfy Registry https://comfyregistry.org

[tool.comfy]
PublisherId = "impactframes"
DisplayName = "ComfyUI-IF_AI_ParlerTTSNode"
Icon = "ğŸ’¥ğŸï¸"
